{% set data = load_setup_py_data() %}

package:
    name: fsplit
    version: {{ data.get('version') }}

build:
    number: 0
    string: py3
    script: python setup.py install --single-version-externally-managed --record=record.txt

source:
    path: ..

requirements:
    host:
        - python
        - pip
    run:
        - bcl2fastq

about:
    home: https://github.com/yodeng/fsplit
    license: BSD
