{% set data = load_setup_py_data() %}

package:
    name: fsplit
    version: {{ data.get('version') }}

build:
    number: 0
    string: py3
    script: {{ PYTHON }} -m pip install -vv .

source:
    path: ..

requirements:
    host:
        - python
        - pip
    run:
        - python
        - pip
        - bcl2fastq

about:
    home: https://github.com/yodeng/fsplit
    license: MIT
